[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
startCommand = "npm start"
context = "Major-Backend"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300           # ← Increased from 100 to 300 seconds
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
