[build]
  base = "Major-Frontend"
  command = "npm run build"
  publish = "Major-Frontend/out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
